### ISSUE TITLE
Add Header/Navbar Component

### ISSUE THREAD

**Issue by bonomoon** [bonomoon/portfolio#13]
> [EPIC-001: Resume Page(API, Client)](https://github.com/bonomoon/portfolio/issues/1) 

![Image](https://user-images.githubusercontent.com/25357575/233857172-3e44ebaa-3c36-4cbb-9b49-3317232a4440.png)

Create reusable header/navbar component.

## Acceptance Criteria

- [x] Is the header component created according to the design mockup?
- [x] When you simply click on the logo which is represented by the 'bonomoon' symbol, this action will redirect you to the main page of the website.
- [x] When you simply click on the link which is represented by the 'Blog', this action should forward you to the blog page of the website.
- [x] When you simply click on the link which is represented by the 'Projects', this action should forward you to the project page of the website.
- [x] When you simply click on the link which is represented by the 'About', this action should forward you to the about page of the website.
- [x] When you simply click on the link which is represented by the 'Resume', this action should forward you to the resume page of the website.
- [x] When you scroll down or up, the header component on the page will remain fixed in position at the top of the page, regardless of whether the user scrolls up or down.
- [x] When you use it on a mobile device, the Navbar's menu list will be condensed into a hamburger button. If you click the button, a menu list modal will be toggled, allowing you to access the items.

## Tasks
- [x] Create navbar component.
- [x] Add nav items and style according to figma mockup.
- [x] Create header component with Navbar and add to default application layout.
- [x] Update to responsive navbar to shorten menu list with a hamburger buttom.
- [x] Test that this component performs the expected behavior.
