### ISSUE TITLE
Create page layout and templates

### ISSUE THREAD

**Issue by bonomoon** [bonomoon/portfolio#14]
![image](https://github.com/bonomoon/portfolio/assets/25357575/747da31c-ccd4-4abd-90e7-bd1cd781890a)

Create reusable page layout, templates, and components.
ex) Header, Footer, Main Container(Page haeder, body, footer)

## Acceptance Criteria

- [x] Is the page created according to the design mockup?
- [x] Components, which are created, are reusable on whole pages? 
- Footer
  - [x] When you simply click on the link which is represented by the 'Github', this action should forward you to my Github home.
  - [x] When you simply click on the link which is represented by the 'LinkedIn', this action should forward you to my LinkedIn profile.
  - [x] When you simply click on the link which is represented by the 'Instagram', this action should forward you to my Instagram profile.
  - [x] When you scroll down to the end of the page, the footer component on the page will show you in position at the bottom of the page.

## Tasks
- [x] Create footer component.
- [x] Add licence, nav items(icons) and style according to figma mockup.
- [x] Create Main component.
- [x] Add Main header, body, footer style and components if they need.
  - [x] Main Header Component(Title, description, children)
  - [x] Main Body Style
  - [x] Main Footer Style and Component(Figma)
- [x] Test that this component performs the expected behavior.
